### ISSUE TITLE
Setup guide-through

### ISSUE THREAD

**Issue by isti03** [EverestAPI/Olympus#1]
# Goals

the aim of this proposal is to help new users get Everest set up quickly

# Implementation

I imagine, this thing could be well implemented with prompts. 

In the examples below, prompts are denoted by the grey "quotes", and buttons are in brackets. 

## If there is no Celeste installation added

**A)** no Celeste installation found

> **Choose Celeste installation folder**
> Olympus could not automatically detect your Celeste installation folder. Please choose it manually
> [Cancel] [Browse]

**B)** one Celeste installation found

> **Celeste installation found**
> `C:\Program Files\Celeste\`
> [Change] [Ok]

**C)** multiple installations are found

> **Choose Celeste installation(s)**
> Olympus found multiple instances of Celeste. Please choose one or more installations or add other ones
> [Cancel] [Ok]

[Ok] redirects to the Install Manager

## An installation is added, but Everest not installed

> **Install Everest**
> In order to install mods for Celeste, you have to install Everest for your installation
> [Cancel] [Install]

**Comment by 0x0ade** [comment]
While I appreciate your proposal, I've already considered creating an "out of box experience" for new Olympus users before releasing it but came to the following conclusions:

- Having a one-time setup guide feels out of place and could become too "in your face" if not enough care is put into it. Everest's "out of box experience" is already walking a fine line.
- This approach heavily discourages exploring the application - not just from a "what can it do" standpoint but also from a "how do I get to this screen" standpoint. I don't want to spoonfeed the user too much.

The "breadcrumbs" (important ! markers) approach that is currently present feels like a good compromise to me. It effectively guides the user to the installation management and Everest installation screen, not only telling them where they should go, but also how to get there in the future and (most importantly) how the "Install Everest" button can no longer be found after installing Everest, replaced by the "Everest, Celeste, <cogwheel>" row. The user is still free to explore the rest of the application, but some menus already require an installation to be selected, guiding the user to the right path anyway. Ideally I should implement those breadcrumbs in more places - "browsing" for an installation if none is present is a good point, but it already is the only button the user can interact with when there are no installations found.

Honestly, only time (and user feedback) can tell if the current approach is good enough or a more "handholdey" approach is necessary. I'd rather put my time and energy elsewhere 😅 

In the future, please discuss user stories and other user experience things in the Celeste Discord server.
