### ISSUE TITLE
Allow display to sleep

### ISSUE THREAD

**Issue by swoolcock** [EverestAPI/Olympus#10]
Currently Olympus uses the default Löve functionality of forcing the display to remain on.  It would be nice to disable this such that I can leave Olympus running and expect the displays to turn off after locking my computer.

From what I can see, this is the required command:
https://love2d.org/wiki/love.window.setDisplaySleepEnabled

I can probably do this myself and make a PR, if it's something you agree on having.

**Comment by 0x0ade** [comment]
Sorry for not noticing this sooner.

I'll set `love.window.setDisplaySleepEnabled` to true except for when an installation is in progress, as I'm worried that allowing for the display to sleep would also allow for laptops to sleep on user inactivity.

**Comment by 0x0ade** [comment]
Thank you for having brought this to my attention :) https://github.com/EverestAPI/Olympus/commit/19a2fded57e909c7fb34822c94528a71b0de0aa3 should fix the issue.
