### ISSUE TITLE
Unable to compile Olympus by myself due to missing Subprocess and NFD

### ISSUE THREAD

**Issue by HurricanePootis** [EverestAPI/Olympus#103]
# System Information
Arch Linux
Love 11.5
Luajit 2.1.1731601260
Dotnet 8.0.11.sdk404

# Problem
I am trying to compile this program fully from scratch. That means not downloading a pre-built version from your website. I am figuring out how to build this fully from scratch in order to fix [https://aur.archlinux.org/packages/olympus-git](https://aur.archlinux.org/packages/olympus-git).

I have gotten here so far:
1. Build the contents of the `sharp/` with `dotnet build -c release`
2. Create a folder called `building`
3. Create `olympus.love` by zipping up the contents of `src/` with `zip -9 -r olympus.zip ./` and then renaming to `olympus.love`
4. Copying `olympus.love`, `./olympus.sh`, `./find-love.sh`, and the `sharp/` folder to `building/` to get the following tree:
```
hurricane@TheCloutPC ~/olympus-git/src/Olympus/building $ tree
.
├── find-love.sh
├── olympus.love
├── olympus.sh
└── sharp
    ├── Mono.Cecil.dll
    ├── Mono.Cecil.Mdb.dll
    ├── Mono.Cecil.Pdb.dll
    ├── Mono.Cecil.Rocks.dll
    ├── MonoMod.dll
    ├── MonoMod.RuntimeDetour.dll
    ├── MonoMod.RuntimeDetour.HookGen.dll
    ├── MonoMod.Utils.dll
    ├── Newtonsoft.Json.dll
    ├── Olympus.Sharp
    ├── Olympus.Sharp.deps.json
    ├── Olympus.Sharp.dll
    ├── Olympus.Sharp.pdb
    ├── Olympus.Sharp.runtimeconfig.json
    └── YamlDotNet.dll

2 directories, 18 files
```

Looking at the `olympus-git`, there used to be a `subprocess-scm-1.rockspec` and a `lua/nfd-scm-1.rockspec` that are now missing from the project.

So my question is how do I get the required subprocess and nfd libraries now.

**Comment by HurricanePootis** [comment]
I read the azure workflow and figured it out. Never mind, sorry for bothering you

**Comment by maddie480** [comment]
Hi 👋 I saw your message on Discord, so just to clarify: the instructions for building involve taking an existing build because they have people wanting to modify Olympus in mind, and taking pre built versions of the dependencies is just simpler to set up the dev environment 😅
