### ISSUE TITLE
[Suggestion] Ship flatpak

### ISSUE THREAD

**Issue by GeopJr** [EverestAPI/Olympus#12]
I saw on the website that under Linux it mentions:
> Pray to dependency satan.

So I decided to make a flatpak for Olympus to solve that.

Here's the YAML:
https://gist.github.com/GeopJr/db90a21346322283a4665bc9f9ec422b

Due to the nature of flatpaks (being sandboxed), I faced some issues with Olympus:
- finder is not able to detect any installations because it first checks `XDG_CONFIG_HOME` which points to `/home/geopjr/.var/app/io.github.EverestAPI.Olympus/config` and not `HOME` which points to `/home/geopjr`

(Following shell is inside the sandbox)
```bash
[📦 io.github.EverestAPI.Olympus]$ echo $XDG_CONFIG_HOME
/home/geopjr/.var/app/io.github.EverestAPI.Olympus/config
[📦 io.github.EverestAPI.Olympus]$ echo $HOME
/home/geopjr
```
<details>
<summary>And here's the log</summary>
[finder]	itch db	/home/geopjr/.var/app/io.github.EverestAPI.Olympus/config/itch/db/butler.db	false<br />[finder]	lutris db	/home/geopjr/.local/share/lutris/pga.db	&lt;same&gt;<br />[finder]	lutris root	/home/geopjr/.var/app/io.github.EverestAPI.Olympus/config/lutris	false<br />[finder]	legendary root	/home/geopjr/.var/app/io.github.EverestAPI.Olympus/config/legendary	false
</details>

- Can't disable the auto-updater. As mentioned in https://github.com/EverestAPI/Olympus/blob/main/src/updater.lua#L19, the auto updater gets disabled when the source is not rw or owner doesn't match user(?), neither of which was I able to achieve inside the flatpak (rw is required else it can't be installed, chown errors with the file as invalid argument (I believe this is because the files are treated or are symlinks)). The updater fails on install anyway.

- Extra data can't be downloaded (no write access) however I can include them in the flatpak.

- There's a warning on start about Olympus not being installed properly (caused by [this function](https://github.com/EverestAPI/Olympus/blob/main/src/modinstaller.lua#L42-L55)). Which again due to the nature of flatpaks, xdg-mime can't access the mimetypes file. However it doesn't seem to be needed at all since the .desktop file handles it well: (Firefox, prompts to open in the Olympus flatpak)
![Screenshot of firefox showing the scheme working](https://user-images.githubusercontent.com/18014039/111903310-92776800-8a39-11eb-9426-d1de4face934.png)

### Info:

Please treat this as a suggestion rather than a bug report as none of the bugs listed actually affect the project directly.
I understand that this puts additional work on the project if maintained officially and closing this issue/declining would be reasonable.

From my testing of the flatpak, I didn't notice anything not working other than what's mentioned above, but I'll list the critical features (that work):
- Selecting the game executable manually
- Installing Everest
- Starting the game from Olympus
- Uninstalling Everest
- GameBanana API + downloading and installing mods
- Removing mods
- Installing Julia & Ahorn
- Map Editor

The flatpak also builds `xdg-utils`, which is not needed as xdg-mime doesn't work as expected in the sandbox, and was added mostly to get rid of the warn `xdg-mime` not found on start. Possibly useless.

I wouldn't mind maintaining the flatpak unofficially (I will probably need to build from source however, instead using the binary, so the flatpak automatically patches the above mentioned "bugs").

(By the way, to test the flatpak use `flatpak-builder ./build ./io.github.EverestAPI.Olympus.yaml --force-clean --install --user`)

### PS
While writing this issue, I noticed that building luajit and love from source was not needed, so I commented them out. But maybe a flatpak could actually solve this dependency mess and replace shipping with those bins.

**Comment by rayzchen** [comment]
bump?

**Comment by AtomHare** [comment]
Now available here: https://flathub.org/apps/io.github.everestapi.Olympus

**Comment by GeopJr** [comment]
Awesome!
