### ISSUE TITLE
[Linux] HiDPI scaling support

### ISSUE THREAD

**Issue by toast003** [EverestAPI/Olympus#79]
I use olympus on my laptop that needs 175% scaling for it's built in screen, and since it doesn't support scaling everything is super tiny

**Comment by AtomHare** [comment]
Do you run under Wayland or X11 ? On 200% scaling, it's super tiny under XWayland (X11) but at the right size under Wayland (Gnome 45)

**Comment by toast003** [comment]
I use kde wayland

**Comment by AtomHare** [comment]
Have you tried Olympus since the latest update ? That's when it started to work under right Wayland

**Comment by toast003** [comment]
Yeah sure enough, flatpak auto updates + me not adding any new mods in a while made me not notice anything changed :sweat_smile:

**Comment by toast003** [comment]
The cursor is still very tiny but I think that's a flatpak on NixOS issue, so all good on your side ^^
