### ISSUE TITLE
Don't try to self-update if installed read-only

### ISSUE THREAD

**Issue by Majora320** [EverestAPI/Olympus#8]
If Olympus is installed to a read-only directory, the self-update feature currently tries to run an install and fails. Instead, it should tell the user to update it via other means.

**Comment by 0x0ade** [comment]
Please give version 21.02.13.02 a try once it's available (within the next few minutes) - if it doesn't fix your issue, feel free to reopen it 😅

**Comment by Majora320** [comment]
Will do! Although to test I'll have to wait until you release another version :)

**Comment by 0x0ade** [comment]
Well, the point of that update is to remove the updater when it's useless, as updating will be handled externally (presumably the package manager). You should be able to determine if it's working fine for your setup by the lack of updating functionality within Olympus itself.

**Comment by Majora320** [comment]
Ah I see, does seem to work as intended then by my testing.
