### ISSUE TITLE
[Suggestion] Detecting NixOS to fix launching

### ISSUE THREAD

**Issue by Petingoso** [EverestAPI/Olympus#94]
On most linux distros, launching modded Celest from Olympus works fine, including with flatpaks which are detected.
NixOS doesn't obey the standard File System Hierarchy and as such launching breaks (lack of finding libc and a namespace?), being needed to manually open steam and run from there.
As such I propose that if the host is Nix and it's a steam installation that it should also call steam to run the app, stopping any breakage.
Pseudo code:
```
(if "NixOS" == file.(/etc/os-release).match(NAME) && path.contains(steamapps))
 steam://run/appid
 ```
 I think a simple edge case like this would to the trick, but there may be a better way.

**Comment by UlyssesZh** [comment]
@Popax21 May be closed since we can now use `OLYMPUS_CELESTE_WRAPPER` (0648f20707043593fac90c6d8837c177ba662963).
